version: 2
updates:
  - package-ecosystem: gomod
    directory: /agent
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /controller
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
